### ISSUE TITLE
Suggested video not show

### ISSUE THREAD

**Issue by louis1706** [ProbablyRaging/hide-youtube-shorts#5] opened 2023-04-04 22:25 UTC
![image](https://user-images.githubusercontent.com/66829532/229936041-887c971f-da72-4519-b68f-f9eec0114286.png)
 see the image 
 
 It's do not always happen but when it's happen only reloading the Extension work

**Comment by zevnda** [comment] 2023-04-12 19:18
Unable to repro. I suggest checking to see if you have any conflicting extensions

**Comment by zevnda** [comment] 2023-04-14 21:46
Reopening as this is likely due to recent UI changes as well

**Comment by louis1706** [comment] 2023-04-15 07:35
> Unable to repro. I suggest checking to see if you have any conflicting extensions

I have only blocker for ads and privacy policy

**Comment by zevnda** [comment] 2023-06-06 22:10
Still unable to reproduce on the new UI so I am going to close this for now.

Feel free to reopen if you have any updates or steps to repro.

**Closed as completed by zevnda** 2023-06-06 22:10 UTC
Labels: bug, investigating
