### ISSUE TITLE
Short on Trending

### ISSUE THREAD

**Issue by Fan4eGGG** [ProbablyRaging/hide-youtube-shorts#21] opened 2023-06-18 21:46 UTC
### Describe the issue

all menu items are enabled, but the shorts are still showing on the trend cluster. what is wrong?
screen: 
![Screenshot_1](https://github.com/ProbablyRaging/hide-youtube-shorts/assets/40491634/31d3231e-800d-44a7-9c96-b1237e33a230)

using latest Opera.

### What version of HYS are you using?

Latest version

### What browsers are you seeing the problem on?

Other

### Latest browser version?

Yes

**Comment by zevnda** [comment] 2023-06-18 21:58
Thank you for bringing this to my attention.

I have actually reverted all changes made to the extension in the previous update, and this will be fixed in `1.6.14` with afc413e290bab2262d16441cbffe574b4f1acd29.

This update should be live on Chrome Web Store within 24 hours.

Thanks again 👌

**Closed as completed by zevnda** 2023-06-18 21:58 UTC
Labels: bug, investigating

**Comment by zevnda** [comment] 2023-06-19 03:13
Sorry, looks like this was caused by a different issue and will be fixed in `1.6.15` instead.
