### ISSUE TITLE
Occasional Removal of Non-Shorts Content in Subscription Feed

### ISSUE THREAD

**Issue by seanhodgins** [ProbablyRaging/hide-youtube-shorts#7] opened 2023-04-14 13:27 UTC
Occasionally when opening the Subscriptions feed, some of the long-form videos that are not Shorts content will be removed along with the Shorts. Seems to be random on which ones are removed, but appears to be the videos located next to the Shorts that are removed.

Can be fixed by using the browsers built in "Reload" button, or by using the plugin "Reload", videos will reappear.

**Comment by zevnda** [comment] 2023-04-14 19:19
Thank you for opening an issue. This is listed in Known Issues #2 and I believe it is due to some changes on YouTube that are slowly being rolled out.

Can you confirm you have these new changes by submitting a screenshot of your Subscriptions page, with the extension turned off.

**Comment by louis1706** [comment] 2023-04-14 20:40
![image](https://user-images.githubusercontent.com/66829532/232150594-593dbf93-ad68-409a-a9d0-1a6218bd7efb.png)

**Comment by zevnda** [comment] 2023-04-14 21:38
@louis1706 this is a different issues than OP's issue. which is mentioned in Known Issues #2. Issues resulting from YouTube's recent UI changes won't be fixed until the rollout is more wide spread.

**Comment by louis1706** [comment] 2023-04-15 14:58
> @louis1706 this is a different issues than OP's issue. which is mentioned in Known Issues #2. Issues resulting from YouTube's recent UI changes won't be fixed until the rollout is more wide spread.

oh okay sorry

**Comment by louis1706** [comment] 2023-04-15 14:59
![image](https://user-images.githubusercontent.com/66829532/232232571-6e56f5f6-9928-4a84-a33f-a555f666a3bf.png)
because today i have got this i supposed than you made a change ?

**Comment by seanhodgins** [comment] 2023-04-16 11:21
> Thank you for opening an issue. This is listed in Known Issues #2 and I believe it is due to some changes on YouTube that are slowly being rolled out.
> 
> Can you confirm you have these new changes by submitting a screenshot of your Subscriptions page, with the extension turned off.

Sure, here is my Subs page with the extension turned off. I'm also subscribed to YouTube Premium. 

![image](https://user-images.githubusercontent.com/4251143/232305856-b9b45eca-71c4-4319-87d1-f0b62200a018.png)

**Comment by zevnda** [comment] 2023-04-16 11:30
Thank you. So this doesn't appear to be the newer UI from what I'm seeing.

When you say it is hiding regular videos, can you explain that or possibly provide proof. A before and after screenshot would be great, just so I can confirm this is indeed an issue as I am not currently able to reproduce it.

I would recommending turning the ext off, going to the subscriptions page and take a screenshot of the before, and then turn the ext on and take a screenshot of the after when regular videos are hidden.

**Comment by zevnda** [comment] 2023-06-06 22:02
Closing as stale.

Feel free to reopen if you have any updates.

**Closed as completed by zevnda** 2023-06-06 22:02 UTC
Labels: bug, investigating
